/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empleado;

import Base_datos.Conectar;
import Menu.Menu_ADM;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar Ortiz
 */
public class Agregare extends javax.swing.JFrame {

    /**
     * Creates new form Usuariocre
     */
    
    int a=0, b=0, refe;
    String j="", Fechana = "", gh = "";    
    public Agregare() {
        initComponents();
        
        int a1=0, b1=0;
        
        ResultSet rs1 = cc.Vertodo("select * from Empleado");
        ResultSet rs2 = cc.Vertodo("select * from Referencia");
        try{
            
            while(rs1.next()){
            a1 = rs1.getInt("Id_empleado");
            gh = rs1.getString("Usuario");
            }
            
            while(rs2.next()){
            b1 = rs2.getInt("Id_Referencia");
                
            }
            
            
            a = a1 + 1;
            b = b1 + 1;
        } catch(Exception e){
            
        } finally{
            cc.cerrar();
        }
        
        jblUsu1.setText(String.valueOf(a));
        jblUsu2.setText(String.valueOf(b));
        jCbSexo.removeAllItems();
        jCbSexo.insertItemAt("Masculino", 0);
        jCbSexo.insertItemAt("Femenino", 1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdReferencia = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtNombre2 = new javax.swing.JTextField();
        jtxtApellido2 = new javax.swing.JTextField();
        jtxtCedula2 = new javax.swing.JTextField();
        jtxtTelefono2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jblUsu2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jtxtCedula = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtxtContrase = new javax.swing.JTextField();
        jtxtCategoria = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jblUsu1 = new javax.swing.JLabel();
        jCbSexo = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();

        jdReferencia.setTitle("Registro Su Referencia");
        jdReferencia.setMinimumSize(new java.awt.Dimension(787, 397));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setText("Registro Referencia");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Nombre:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 121, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Apellido:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 162, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Cedula:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 196, -1, -1));
        jPanel3.add(jtxtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 124, 220, -1));
        jPanel3.add(jtxtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 165, 220, -1));
        jPanel3.add(jtxtCedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 199, 220, -1));
        jPanel3.add(jtxtTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 220, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jButton5.setText("Guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, 50));

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver 1.png"))); // NOI18N
        jButton6.setText("Volver");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 120, 40));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("Telefono:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 237, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("N. Registro");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jblUsu2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(jblUsu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 58, 42));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 390));

        javax.swing.GroupLayout jdReferenciaLayout = new javax.swing.GroupLayout(jdReferencia.getContentPane());
        jdReferencia.getContentPane().setLayout(jdReferenciaLayout);
        jdReferenciaLayout.setHorizontalGroup(
            jdReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jdReferenciaLayout.setVerticalGroup(
            jdReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Empleados");
        setIconImage(getIconImage());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Registro Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 121, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 162, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Cedula:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 196, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Fecha nacimiento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 239, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Sexo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 285, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Usuario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Contraseña:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, 20));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Categoria:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, 20));
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 114, 220, 30));
        jPanel1.add(jtxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 155, 220, 30));
        jPanel1.add(jtxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 189, 220, 30));
        jPanel1.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 320, 220, 30));
        jPanel1.add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 361, 220, 30));
        jPanel1.add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 220, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Insertar.png"))); // NOI18N
        jButton1.setText("Referencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 160, 60));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Añadir.png"))); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 140, 60));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver 1.png"))); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 120, 60));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Direccion:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 327, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Telefono");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 368, -1, -1));
        jPanel1.add(jtxtContrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 220, 30));
        jPanel1.add(jtxtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 220, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("N. Registro");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jblUsu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jblUsu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 55, 22));

        jCbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jCbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 279, 220, 30));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 220, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));


        return retValue;
    }
    
    public static String fecha(){
        
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd");
        
        return formato.format(fecha);
        
    }
    
    //Boton volver al menu
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        this.hide();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    //Boto para guardar El empleado
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Date fecha = null;
        String Codigo = String.valueOf(a);
        String Nombre = jtxtNombre.getText();
        String Apellido = jtxtApellido.getText();
        String Cedula = jtxtCedula.getText();
        String ele = "";
        if(jCbSexo.getSelectedIndex() == 0){
            ele = "m";
        } else if(jCbSexo.getSelectedIndex() == 1){
            ele = "f";
        }
        String Sexo = ele;
        String Direccion = jtxtDireccion.getText();
        String Telefono = jtxtTelefono.getText();
        String Usuario = jtxtUsuario.getText();
        String Contrase = jtxtContrase.getText();
        String Fechaini = fecha();
        SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd");
        
        try{
        String fechana = "";
        fechana = formato.format(jDateChooser1.getDate());
        
        String Categoria = jtxtCategoria.getText();
        if(fechana.equals("")){
            JOptionPane.showMessageDialog(null, "Faltan datos por introducir!", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
        } else {
             
        
        if(Nombre.equals("") || Apellido.equals("") || Cedula.equals("") || Sexo.equals("") || Direccion.equals("") || Telefono.equals("") || Usuario.equals("") || Contrase.equals("") || Categoria.equals("")){
        
            JOptionPane.showMessageDialog(null, "Faltan datos por introducir!", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            try{

                if(this.j.equals("Leno")){
                    
                    if(Usuario.equals(gh)){
                    JOptionPane.showMessageDialog(null, "El usuario esta registrado", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                    try{
                    cc.Insert("insert into Empleado(Id_Empleado, nombre, apellido, cedula, fecha_naci, Sexo, Direccion, Telefono, usuario, contrasena, fecha_ini, categoria, id_referencia)"
                            + "values ("+Codigo+", '"+Nombre+"', '"+Apellido+"', '"+Cedula+"', '"+fechana+"', '"+Sexo+"', '"+Direccion+"', '"+Telefono+"', '"+Usuario+"', '"+Contrase+"', '"+Fechaini+"', '"+Categoria+"', "+this.b+")");
                    this.j = "";
                    
                    jtxtNombre.setText("");
                    jtxtApellido.setText("");
                    jtxtCedula.setText("");
                    ele = "";
                    jtxtDireccion.setText("");
                    jtxtTelefono.setText("");
                    jtxtTelefono.setText("");
                    jtxtUsuario.setText("");
                    jtxtContrase.setText("");
                    jDateChooser1.setDate(fecha);
                    jtxtCategoria.setText("");
                    this.b = 0;
                    this.hide();
                     }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No Se Agrego El Registro", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
                } finally{
                    cc.cerrar();
                }
                    }
                
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Faltan por llenar la referencia!", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
                
                }
            }catch(Exception e){

            } finally{
                cc.cerrar();
            }
        }
        }} catch(Exception e){
        JOptionPane.showMessageDialog(null, "Faltan datos por introducir!", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    //Boton para guardar la referencia
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        
        String Codigo = String.valueOf(b);
        String Nombre = jtxtNombre2.getText();
        String Apellido = jtxtApellido2.getText();
        String Cedula = jtxtCedula2.getText();
        String Telefono = jtxtTelefono2.getText();
        
        if(Nombre.equals("") || Apellido.equals("") || Cedula.equals("") || Telefono.equals("")){
        
            JOptionPane.showMessageDialog(null, "Faltan datos por introducir!", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
                try{
                    
                    cc.Insert("insert into Referencia(id_referencia, nombre, apellido, cedula, telefono)"
                            + "values ("+Codigo+", '"+Nombre+"', '"+Apellido+"', '"+Cedula+"', '"+Telefono+"')");
                    this.j= "Leno";
                    jtxtNombre2.setText("");
                    jtxtApellido2.setText("");
                    jtxtCedula2.setText("");
                    jtxtTelefono2.setText("");
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No Se Agrego El Registro", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
                } finally{
                    cc.cerrar();
                }
                jdReferencia.hide();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    //Para llamar a referencia
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        jdReferencia.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //Boton para volver a agregar empleado
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        jdReferencia.hide();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCbSexo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jblUsu1;
    private javax.swing.JLabel jblUsu2;
    private javax.swing.JDialog jdReferencia;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtApellido2;
    private javax.swing.JTextField jtxtCategoria;
    private javax.swing.JTextField jtxtCedula;
    private javax.swing.JTextField jtxtCedula2;
    private javax.swing.JTextField jtxtContrase;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNombre2;
    private javax.swing.JTextField jtxtTelefono;
    private javax.swing.JTextField jtxtTelefono2;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables

    Conectar cc = new Conectar();

}
