/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Factura;

import Base_datos.Conectar_Oracle;
import Empleado.Agregare;
import static Solicitud.Solicitud.jlCliente;
import static Solicitud.Solicitud.jtxtMonto;
import static Solicitud.Solicitud.jtxtPlazo;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar Ortiz
 */
public class Factorizacion extends javax.swing.JFrame {

    /**
     * Creates new form Factorizacion
     */
    
     int a, codigoa;
    
    public Factorizacion() {
        initComponents();
        
        int a1=0;

            try {
            ResultSet rs1;
                try {
                    rs1 = cc.Vertodo("select * from Facturacion");
                    
                    while(rs1.next()){
                        a1 = rs1.getInt("ID_Factura");
                
                    }
                    
                    ResultSet rs = cc.Vertodo("select * from Amortizacion");
                    DefaultTableModel model = new DefaultTableModel();
                    jtTabla.setModel(model);
                    model.setColumnIdentifiers(new Object[]{"Codigo de la Amortizacion", "Codigo del Prestamo", "Cuotas", "Capital", "Interes", "Monto"});
                
            
                    while(rs.next()){

                        model.addRow(new Object[]{rs.getInt("ID_Amortizacion"), rs.getInt("ID_Prestamo"), rs.getInt("Cuotas"), rs.getInt("Capital"), rs.getInt("Interes"), rs.getInt("Monto")});

                    }
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Agregare.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        } catch (SQLException ex) {
        }
        
        a = a1 + 1;
        jLabel3.setText(String.valueOf(a));
        jLabel10.setText(fecha());
        
    }
    
    //Metodo par ala fecha
    public static String fecha(){
        
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        
        return formato.format(fecha);
        
    }
    
    public void Buscar(){
            
            int a1=0;

            
            
        try {
            ResultSet rs1;
                try {
                    rs1 = cc.Vertodo("select * from Facturacion");
                    
                    while(rs1.next()){
                        a1 = rs1.getInt("ID_Factura");
                
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Agregare.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        } catch (SQLException ex) {
        }
        
        a = a1 + 1;
        jLabel3.setText(String.valueOf(a));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdBuscar = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jtxtBuscar = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jbtMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jrbNombre = new javax.swing.JRadioButton();
        jrbCodigo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jtxtCliente = new javax.swing.JLabel();
        jtxtPrestamo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jdBuscar.setMinimumSize(new java.awt.Dimension(1120, 700));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 109, 210, -1));

        jbtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 150, 60));

        jbtMostrar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mostrar.png"))); // NOI18N
        jbtMostrar.setText("Mostrar Todo");
        jbtMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 210, 60));

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, 1090, -1));

        jrbNombre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbNombre.setText("Codigo Prestamo");
        jPanel2.add(jrbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 200, -1));

        jrbCodigo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jrbCodigo.setSelected(true);
        jrbCodigo.setText("Codigo Amortización");
        jPanel2.add(jrbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel6.setText("Consultar Amortización");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver 1.png"))); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 610, 140, 50));

        jButton8.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar.png"))); // NOI18N
        jButton8.setText("Seleccionar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 180, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 680));

        javax.swing.GroupLayout jdBuscarLayout = new javax.swing.GroupLayout(jdBuscar.getContentPane());
        jdBuscar.getContentPane().setLayout(jdBuscarLayout);
        jdBuscarLayout.setHorizontalGroup(
            jdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdBuscarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdBuscarLayout.setVerticalGroup(
            jdBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdBuscarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Facturacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Codigo de la factura:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 40, 31));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Amortizacion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Fecha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 207, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 128, 140, 40));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 150, 40));

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver 1.png"))); // NOI18N
        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jtxtCliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jtxtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 140, 30));

        jtxtPrestamo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jtxtPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 130, 40));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 150, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton para cerrar la ventana
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        this.hide();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    //Boton para guardar el registro
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        String codigo = String.valueOf(this.a);
        String Codigoa = String.valueOf(this.codigoa);
        String sql = "insert into Facturacion values (?, ?, ?)";
        Connection cn = null;
        PreparedStatement insert;
        java.util.Date date = new java.util.Date();
        long t = date.getTime();
        java.sql.Date sqlDate = new java.sql.Date(t);
        
        try{
            
            if(Codigoa.equals("")){
        
            JOptionPane.showMessageDialog(null, "Debe Elegir la Amortizacion a Facturar!", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
            
        }else{  
                
                try{
                    
                
                    try{
                    
                        cn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ADM","Administrador");
                        insert = cn.prepareStatement(sql);
                        
                        insert.setInt(1, Integer.parseInt(codigo));
                        insert.setInt(2, Integer.parseInt(Codigoa));
                        insert.setDate(3, sqlDate);
                        insert.executeUpdate();
                    
                        JOptionPane.showMessageDialog(null, "Se Agrego El Registro", "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
                        
                    this.codigoa = 0;
                    Buscar();
                    
                    }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No Se Agrego El Registro " + e, "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
                    } finally{
                        cc.close();
                    } 
     
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error" + e, "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
                }
                    
        }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error" + e, "Sistema De Prestamo", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    //Boton para buscar al amortizacion
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        jdBuscar.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed

        String nombre = jtxtBuscar.getText();

        if(jrbNombre.isSelected() == false && jrbCodigo.isSelected() == false){
            JOptionPane.showMessageDialog(null, "No a elegino ningun tipo a buscar", "Sistema de prestamo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(jrbNombre.isSelected() == true && jrbCodigo.isSelected() == true){
                JOptionPane.showMessageDialog(null, "Solo puede sellecionar una sola opcion", "Sistema de prestamo", JOptionPane.INFORMATION_MESSAGE);
            } else if(jrbNombre.isSelected() == true){
                if(nombre.equals("")){
                    JOptionPane.showMessageDialog(null, "No a escrito el nombre a buscar", "Sistema de prestamo", JOptionPane.INFORMATION_MESSAGE);
                } else{
                    char k = nombre.charAt(0);
                    if(Character.isLetter(k)){
                        JOptionPane.showMessageDialog(null, "Solo Puede introducir Numeros", "Sistema de prestamo", JOptionPane.INFORMATION_MESSAGE);
                    } else{
                        try{
                            ResultSet rs = cc.Vertodo("select * from Amortizacion where ID_Prestamo = "+nombre+"");
                            DefaultTableModel model = new DefaultTableModel();
                            jtTabla.setModel(model);
                            model.setColumnIdentifiers(new Object[]{"Codigo de la Amortizacion", "Codigo del Prestamo", "Cuotas", "Capital", "Interes", "Monto"});
                
                            while(rs.next()){

                                model.addRow(new Object[]{rs.getInt("ID_Amortizacion"), rs.getInt("ID_Prestamo"), rs.getInt("Cuotas"), rs.getInt("Capital"), rs.getInt("Interes"), rs.getInt("Monto")});

                            }

                        } catch(Exception e){

                        } finally{
                            cc.close();
                        }
                    }
                }
            }else{
                if(nombre.equals("")){
                    JOptionPane.showMessageDialog(null, "No a escrito el codigo a buscar");
                } else{
                    try{
                        int ho = Integer.parseInt(nombre);
                        if(ho >= 0){
                            ResultSet rs = cc.Vertodo("select * from Amortizacion where ID_Amortizacion = "+nombre+"");
                            DefaultTableModel model = new DefaultTableModel();
                            jtTabla.setModel(model);
                            model.setColumnIdentifiers(new Object[]{"Codigo de la Amortizacion", "Codigo del Prestamo", "Cuotas", "Capital", "Interes", "Monto"});
                
                            while(rs.next()){

                                model.addRow(new Object[]{rs.getInt("ID_Amortizacion"), rs.getInt("ID_Prestamo"), rs.getInt("Cuotas"), rs.getInt("Capital"), rs.getInt("Interes"), rs.getInt("Monto")});

                            }
                        }

                    } catch(Exception e){

                        JOptionPane.showMessageDialog(null, "Solo puede introducir numeros", "Sistema de prestamo", JOptionPane.INFORMATION_MESSAGE);

                    } finally{
                        cc.close();
                    }
                }
            }
        }
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMostrarActionPerformed
        try{

            ResultSet rs = cc.Vertodo("select * from Amortizacion");
            DefaultTableModel model = new DefaultTableModel();
            jtTabla.setModel(model);
            model.setColumnIdentifiers(new Object[]{"Codigo de la Amortizacion", "Codigo del Prestamo", "Cuotas", "Capital", "Interes", "Monto"});
                
            while(rs.next()){

                model.addRow(new Object[]{rs.getInt("ID_Amortizacion"), rs.getInt("ID_Prestamo"), rs.getInt("Cuotas"), rs.getInt("Capital"), rs.getInt("Interes"), rs.getInt("Monto")});

            }

        } catch(Exception e){

        } finally{
            cc.close();
        }
    }//GEN-LAST:event_jbtMostrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jdBuscar.hide();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        int j = jtTabla.getSelectedRow();
        String codigo = "";

        try{
            if(j==-1){
                JOptionPane.showMessageDialog(null, "Debe de seleccionar un registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                if(j >=0 ){

                    codigo = jtTabla.getValueAt(j, 0).toString();
                    codigoa = Integer.parseInt(codigo);
                    jdBuscar.hide();

                }
            }

        }catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factorizacion().setVisible(true);
            }
        });
    }
    
    Conectar_Oracle cc = new Conectar_Oracle();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtMostrar;
    private javax.swing.JDialog jdBuscar;
    private javax.swing.JRadioButton jrbCodigo;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JTable jtTabla;
    public static javax.swing.JTextField jtxtBuscar;
    private javax.swing.JLabel jtxtCliente;
    private javax.swing.JLabel jtxtPrestamo;
    // End of variables declaration//GEN-END:variables
}
